/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SectionsRouteRouteImport } from './routes/_sections/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SectionsTasksIndexRouteImport } from './routes/_sections/tasks/index'
import { Route as SectionsSettingsIndexRouteImport } from './routes/_sections/settings/index'
import { Route as SectionsHabitsIndexRouteImport } from './routes/_sections/habits/index'

const SectionsRouteRoute = SectionsRouteRouteImport.update({
  id: '/_sections',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionsTasksIndexRoute = SectionsTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => SectionsRouteRoute,
} as any)
const SectionsSettingsIndexRoute = SectionsSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => SectionsRouteRoute,
} as any)
const SectionsHabitsIndexRoute = SectionsHabitsIndexRouteImport.update({
  id: '/habits/',
  path: '/habits/',
  getParentRoute: () => SectionsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/habits': typeof SectionsHabitsIndexRoute
  '/settings': typeof SectionsSettingsIndexRoute
  '/tasks': typeof SectionsTasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/habits': typeof SectionsHabitsIndexRoute
  '/settings': typeof SectionsSettingsIndexRoute
  '/tasks': typeof SectionsTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_sections': typeof SectionsRouteRouteWithChildren
  '/_sections/habits/': typeof SectionsHabitsIndexRoute
  '/_sections/settings/': typeof SectionsSettingsIndexRoute
  '/_sections/tasks/': typeof SectionsTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/habits' | '/settings' | '/tasks'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/habits' | '/settings' | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/_sections'
    | '/_sections/habits/'
    | '/_sections/settings/'
    | '/_sections/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SectionsRouteRoute: typeof SectionsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_sections': {
      id: '/_sections'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof SectionsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sections/tasks/': {
      id: '/_sections/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof SectionsTasksIndexRouteImport
      parentRoute: typeof SectionsRouteRoute
    }
    '/_sections/settings/': {
      id: '/_sections/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SectionsSettingsIndexRouteImport
      parentRoute: typeof SectionsRouteRoute
    }
    '/_sections/habits/': {
      id: '/_sections/habits/'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof SectionsHabitsIndexRouteImport
      parentRoute: typeof SectionsRouteRoute
    }
  }
}

interface SectionsRouteRouteChildren {
  SectionsHabitsIndexRoute: typeof SectionsHabitsIndexRoute
  SectionsSettingsIndexRoute: typeof SectionsSettingsIndexRoute
  SectionsTasksIndexRoute: typeof SectionsTasksIndexRoute
}

const SectionsRouteRouteChildren: SectionsRouteRouteChildren = {
  SectionsHabitsIndexRoute: SectionsHabitsIndexRoute,
  SectionsSettingsIndexRoute: SectionsSettingsIndexRoute,
  SectionsTasksIndexRoute: SectionsTasksIndexRoute,
}

const SectionsRouteRouteWithChildren = SectionsRouteRoute._addFileChildren(
  SectionsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SectionsRouteRoute: SectionsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
